In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr.shape
arr.max()

5

In [4]:
l = [1,2,4,5.5,"hello"]
l = np.array(l)
l

array(['1', '2', '4', '5.5', 'hello'], dtype='<U32')

In [5]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a = np.array(a)

In [6]:
a.shape # 3,3
a.dtype # int 64

dtype('int64')

In [7]:
arr = np.arange(1,21,2) # same as range function
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [8]:
arr = np.zeros((3,2)) # row,col
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
arr = np.linspace(1,5,10)# we have to provide a range and how many number b/w them
# 1-5 range and 10 elements b/w the range 
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

# Random

In [11]:
arr = np.random.rand(1,5,6)

arr

array([[[0.94891597, 0.27903968, 0.24531323, 0.25180698, 0.68347033,
         0.17235279],
        [0.09321941, 0.32283313, 0.04844331, 0.91345819, 0.18782443,
         0.83451423],
        [0.16707294, 0.84445205, 0.02277062, 0.83752795, 0.63319465,
         0.28412289],
        [0.63540046, 0.49551964, 0.42029691, 0.96399044, 0.76350878,
         0.9252868 ],
        [0.63923516, 0.37739362, 0.04753313, 0.55345224, 0.07566588,
         0.21596606]]])

In [12]:
arr = np.random.randint(0,11,5)
arr

array([5, 3, 1, 3, 3])

In [13]:
arr = [[1,2,3],[4,5,6],[7,8,9]]
np.sum(arr,axis=0) # 0-column wise sum
np.sum(arr,axis=1)# 1=row wise sum


array([ 6, 15, 24])

In [14]:
np.argmin(arr) # returns the index of the min element



0

In [15]:
np.argmax(arr)

8

# Reshaping the array

In [16]:
arr = np.arange(1,31)
arr.reshape(6,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# Matrix Sllicing

In [17]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [18]:
arr[2:4,1:3] 

array([[12, 13],
       [17, 18]])

In [19]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

# Array operations

In [20]:
a1 = np.arange(1,6)
a2 = np.arange(6,11)

In [21]:
a1

array([1, 2, 3, 4, 5])

In [22]:
a2

array([ 6,  7,  8,  9, 10])

In [23]:
a1+a2 # should be same in size

array([ 7,  9, 11, 13, 15])

In [24]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [25]:
# Deep ans shallow copy
a = np.arange(1,16)
slice = a[2:10]
slice = slice * 10

In [26]:
slice # shallow copy

array([ 30,  40,  50,  60,  70,  80,  90, 100])

In [27]:
a # no change in the array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
b = a

In [29]:
b[5] = 99 # deep copy

In [30]:
a # since the elelment 5 is changed now 

array([ 1,  2,  3,  4,  5, 99,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
b 

array([ 1,  2,  3,  4,  5, 99,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
b = a.copy() # to avoid use copy function
b[5] = 1002

In [33]:
a

array([ 1,  2,  3,  4,  5, 99,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
b

array([   1,    2,    3,    4,    5, 1002,    7,    8,    9,   10,   11,
         12,   13,   14,   15])

In [35]:
# Matrix multiplication
a = np.array([[1,2,3],[4,5,6]]) #2,3

In [36]:
b = np.array([[7,8,9],[10,11,12],[5,6,7]]) # 3,3

In [37]:
a @ b # first mat col should be = row of other mat here 3=3

array([[ 42,  48,  54],
       [108, 123, 138]])

In [38]:
np.dot(a,b) # same as a @ b

array([[ 42,  48,  54],
       [108, 123, 138]])

In [39]:
# stacking 
np.vstack((a,b)) # vertical stack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 5,  6,  7]])

In [40]:
b = np.array([[7,8,9],[10,11,12],[5,6,7]]) 
a = np.array([[7,8,9],[10,11,12],[5,6,7]])
A = np.hstack((a,b))
A

array([[ 7,  8,  9,  7,  8,  9],
       [10, 11, 12, 10, 11, 12],
       [ 5,  6,  7,  5,  6,  7]])